version: "3"
services:
  backend-db-seed:
    container_name: "product-build-db"
    image: nateai/challenge-ios-build-db:1.0.0
    environment:
      - DATABASE_URL=postgres://productUser:password@postgres:5432/product
    build:
      dockerfile: Dockerfile.build.db
      context: .
    depends_on:
      - postgres

  backend-rest:
    container_name: "product-rest-service"
    image: nateai/challenge-ios-rest:1.0.0
    environment:
      - DATABASE_URL=postgres://productUser:password@postgres:5432/product
    build:
      dockerfile: Dockerfile.rest
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - backend-db-seed

  backend-graph:
    container_name: "product-graph-service"
    image: nateai/challenge-ios-graph:1.0.0
    environment:
      - DATABASE_URL=postgres://productUser:password@postgres:5432/product
    build:
      dockerfile: Dockerfile.graph
      context: .
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - backend-db-seed

  postgres:
    container_name: "product-db"
    image: postgres:12.3
    environment:
      - POSTGRES_USER=productUser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product
      - PGDATA=/data
    ports:
      - 5432:5432
